# -*- coding: utf-8 -*-
"""Marathe_Group.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uY7I1j39TUhFbVsYwe2z4reD1UScrlE0
"""
import streamlit as st
import pandas as pd
import datetime
import os



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import datetime
# import requests
# 
# # ----------------- PAGE CONFIG -----------------
# st.set_page_config(page_title="Marathe Group", page_icon="🏢", layout="wide")
# 
# # ----------------- HEADER -----------------
# st.markdown("<h1 style='text-align:center;color:#2E4053;'>🏢 Marathe Group</h1>", unsafe_allow_html=True)
# st.markdown("<h4 style='text-align:center;color:#566573;'>Luxury Living • Trusted Legacy</h4>", unsafe_allow_html=True)
# st.image("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
#          use_column_width=True, caption="Building Dreams Since 1995")
# st.markdown("---")
# 
# # ----------------- MISSION & VISION -----------------
# st.markdown("<h2 style='text-align:center;color:#1F618D;'>🌟 Our Mission & Vision</h2>", unsafe_allow_html=True)
# col1, col2 = st.columns(2)
# with col1:
#     st.markdown("""
#     ### 🎯 **Our Mission**
#     > To craft homes that embody comfort, elegance, and reliability —
#     > while nurturing long-term trust and transparent relationships.
#     > We strive to provide every family a home that mirrors their dreams.
#     """)
# with col2:
#     st.markdown("""
#     ### 👁️ **Our Vision**
#     > To become a benchmark in sustainable and customer-centric development,
#     > redefining skylines across India through innovation, trust, and excellence.
#     """)
# st.markdown("---")
# 
# # ----------------- PROJECT DATA -----------------
# ongoing_projects = [
#     {"name": "Marathe Sapphire", "location": "Titwala (E)",
#      "address": "1st Floor Sales Office, Swami Vivekanand Chowk Road, Titwala East, Maharashtra",
#      "image": "https://raw.githubusercontent.com/Rita1791/Marathe-Group/main/images/marathe_sapphire.jpg"},
#     {"name": "Marathe Tower", "location": "Titwala (E)",
#      "address": "Ground Floor Sales Office, Digi1 Road, Titwala East, Maharashtra",
#      "image": "https://github.com/Rita1791/Marathe-Group/blob/main/Marathe%20Tower.jpg?raw=true"},
#     {"name": "Marathe Pride", "location": "Ambernath (E)",
#      "address": "Plot No. 220 & 221, Marathe Pride, Ambernath East, Maharashtra",
#      "image": "https://raw.githubusercontent.com/Rita1791/Marathe-Group/main/images/marathe_pride.jpg"}
# ]
# 
# completed_projects = [
#     {"name": "Marathe Empress", "location": "Titwala (E)",
#      "address": "Jagat Naka, Titwala East, Maharashtra",
#      "image": "https://github.com/Rita1791/Marathe-Group/blob/main/Marathe%20Empress.webp?raw=true"},
#     {"name": "Marathe Height", "location": "Titwala (E)",
#      "address": "Near Ghar Aangan, Titwala East, Maharashtra",
#      "image": "https://github.com/Rita1791/Marathe-Group/blob/main/marathe%20Height.png?raw=true"},
#     {"name": "Marathe Fortune", "location": "Titwala (E)",
#      "address": "Ganesh Mandir Road, Titwala East, Maharashtra",
#      "image": "https://raw.githubusercontent.com/Rita1791/Marathe-Group/refs/heads/main/Marathe%20Fortune.avif"},
#     {"name": "Marathe Empire", "location": "Titwala (E)",
#      "address": "Near Mahaganpati Hospital, Titwala East, Maharashtra",
#      "image": "https://github.com/Rita1791/Marathe-Group/blob/main/Marathe%20Empire.jpg?raw=true"},
#     {"name": "Marathe Elenza", "location": "Shahad (W)",
#      "address": "Ground Floor Sales Office, Shahad West, Maharashtra",
#      "image": "https://raw.githubusercontent.com/Rita1791/Marathe-Group/main/images/marathe_elenza.jpg"}
# ]
# 
# # ----------------- TABS -----------------
# tab1, tab2, tab3, tab4 = st.tabs(
#     ["🏗️ Ongoing Projects", "🏠 Completed Projects", "📝 Enquiry Form", "📞 Contact Info"]
# )
# 
# # ----------------- ONGOING -----------------
# with tab1:
#     st.subheader("Ongoing Projects")
#     for p in ongoing_projects:
#         st.image(p["image"], caption=p["name"], use_column_width=True)
#         st.markdown(f"🏗️ **Project:** {p['name']} \n📍 **Location:** {p['location']} \n🏠 **Address:** {p['address']}")
#         st.markdown("---")
# 
# # ----------------- COMPLETED -----------------
# with tab2:
#     st.subheader("Completed Projects")
#     for p in completed_projects:
#         st.image(p["image"], caption=p["name"], use_column_width=True)
#         st.markdown(f"🏢 **Project:** {p['name']} \n📍 **Location:** {p['location']} \n🏠 **Address:** {p['address']}")
#         st.markdown("---")
# 
# # ----------------- ENQUIRY FORM -----------------
# with tab3:
#     st.subheader("Flat Enquiry Form 🏡")
#     st.write("Please fill the form below and our team will contact you soon:")
# 
#     GOOGLE_SHEETS_URL = "https://script.google.com/macros/s/AKfycbweNZlJ6blTGMpqX5aJWi_xBAAkgKXdWvpeuK6j7KAvOvwYt1Zh1c1mhnkzfsC3huaE/exec"
# 
#     with st.form("enquiry_form"):
#         name = st.text_input("Full Name")
#         phone = st.text_input("Phone Number")
#         project = st.selectbox("Select Project", [p["name"] for p in ongoing_projects + completed_projects])
#         message = st.text_area("Additional Message (optional)")
#         submit = st.form_submit_button("Submit")
# 
#         if submit:
#             if name and phone:
#                 data = {"name": name, "phone": phone, "project": project, "message": message}
#                 try:
#                     response = requests.post(GOOGLE_SHEETS_URL, json=data)
#                     if response.status_code == 200:
#                         st.success(f"✅ Thank you {name}! Your enquiry for **{project}** has been submitted successfully.")
#                     else:
#                         st.error("Submission failed – please try again later.")
#                 except Exception as e:
#                     st.error("Error connecting to Google Sheet. Check your Web App URL.")
#             else:
#                 st.error("Please enter both Name and Phone Number.")
# 
# # ----------------- CONTACT -----------------
# with tab4:
#     st.subheader("Contact Information")
#     st.markdown("""
#     ⏰ **Working Hours:** 10:00 AM – 07:00 PM (Mon – Sun)
#     📞 **Contact Number:** [+91 7045871101](tel:+917045871101)
#     💬 **WhatsApp:** [Chat Now](https://wa.me/917045871101)
#     ✉️ **Email:** marathegroup1101@gmail.com
#     👤 **Owner:** Parasana Marathe
#     👥 **Manager:** Padma Rawat
#     """)
#     st.caption("© 2025 Marathe Group | Designed by Ritika Rawat 💻")
#


